# Generated by Django 6.0 on 2026-01-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
